// Ported from gpuweb/cts src/webgpu/api/validation/capability_checks/limits/maxStorageTexturesPerShaderStage.spec.ts @ b507bd117e53db86f2fb52d0d858d3ae7d684a85
#include "cts/test.h"
#include "limit_utils.h"
using namespace cts; using namespace cts::capability_limits;
namespace {
class MaxStorageTexturesPerShaderStageTest : public LimitTest { public: const char* limitName() const override { return "maxStorageTexturesPerShaderStage"; } };
TestGroup<MaxStorageTexturesPerShaderStageTest> testGroup = MakeTestGroup<MaxStorageTexturesPerShaderStageTest>("api,validation,capability_checks,limits,maxStorageTexturesPerShaderStage", "API Validation Tests for maxStorageTexturesPerShaderStage.");
std::vector<LimitRequestEntry> extraLimits(MaxStorageTexturesPerShaderStageTest& t, std::string_view limitTest) { std::vector<LimitRequestEntry> v = {adapterLimitRequest("maxBindingsPerBindGroup"), adapterLimitRequest("maxBindGroups")}; addMaximumLimitUpToDependentLimit(t, v, "maxStorageTexturesInFragmentStage", "maxStorageTexturesPerShaderStage", limitTest); addMaximumLimitUpToDependentLimit(t, v, "maxStorageTexturesInVertexStage", "maxStorageTexturesPerShaderStage", limitTest); return v; }
void skipStorageTextures(MaxStorageTexturesPerShaderStageTest& t, WGPUShaderStage visibility, uint64_t value) { WGPUCompatibilityModeLimits compat = WGPU_COMPATIBILITY_MODE_LIMITS_INIT; const WGPULimits limits = queryLimits(t.device(), &compat); if ((visibility & WGPUShaderStage_Fragment) && compat.maxStorageTexturesInFragmentStage != WGPU_LIMIT_U32_UNDEFINED && limits.maxStorageTexturesPerShaderStage > compat.maxStorageTexturesInFragmentStage && compat.maxStorageTexturesInFragmentStage < value) t.skip("maxStorageTexturesInFragmentStage is less than required storage textures"); if ((visibility & WGPUShaderStage_Vertex) && compat.maxStorageTexturesInVertexStage != WGPU_LIMIT_U32_UNDEFINED && limits.maxStorageTexturesPerShaderStage > compat.maxStorageTexturesInVertexStage && compat.maxStorageTexturesInVertexStage < value) t.skip("maxStorageTexturesInVertexStage is less than required storage textures"); }
CTS_TEST(testGroup, "createBindGroupLayout,at_over").params([](ParamsBuilder u) { return kMaximumLimitBaseParams(u).combine("visibility", shaderStageCombinationWithStageValues()).combine("access", storageTextureAccessValues()).filter([](const ParamRecord& p) { return storageTextureAccessAllowedInVisibility(static_cast<WGPUShaderStage>(valueAs<uint64_t>(*findParam(p, "visibility"))), valueAs<std::string>(*findParam(p, "access"))); }).combine("order", kReorderOrderValues()); }).fn([](MaxStorageTexturesPerShaderStageTest& t) {
    const auto visibility = static_cast<WGPUShaderStage>(t.param<uint64_t>("visibility")); const std::string access = t.param<std::string>("access"); const ReorderOrder order = parseReorderOrder(t.param<std::string>("order")); const std::string limitTest = t.param<std::string>("limitTest");
    t.testDeviceWithRequestedMaximumLimits(limitTest, t.param<std::string>("testValueName"), [&](const MaximumLimitTestInputs& in) { if (t.getAdapterLimit("maxBindingsPerBindGroup") < in.testValue) t.skip("maxBindingsPerBindGroup is less than test value"); skipStorageTextures(t, visibility, in.testValue); t.expectValidationErrorOnLimitDevice([&] { createPerStageBindGroupLayout(t, visibility, parseStorageTextureKind(access), order, in.testValue); }, in.shouldError); }, extraLimits(t, limitTest));
});
CTS_TEST(testGroup, "createPipelineLayout,at_over").params([](ParamsBuilder u) { return kMaximumLimitBaseParams(u).combine("visibility", shaderStageCombinationWithStageValues()).combine("access", storageTextureAccessValues()).filter([](const ParamRecord& p) { return storageTextureAccessAllowedInVisibility(static_cast<WGPUShaderStage>(valueAs<uint64_t>(*findParam(p, "visibility"))), valueAs<std::string>(*findParam(p, "access"))); }).combine("order", kReorderOrderValues()); }).fn([](MaxStorageTexturesPerShaderStageTest& t) {
    const auto visibility = static_cast<WGPUShaderStage>(t.param<uint64_t>("visibility")); const std::string access = t.param<std::string>("access"); const ReorderOrder order = parseReorderOrder(t.param<std::string>("order")); const std::string limitTest = t.param<std::string>("limitTest");
    t.testDeviceWithRequestedMaximumLimits(limitTest, t.param<std::string>("testValueName"), [&](const MaximumLimitTestInputs& in) { skipStorageTextures(t, visibility, in.testValue); testPerStageCreatePipelineLayout(t, visibility, parseStorageTextureKind(access), order, in); }, extraLimits(t, limitTest));
});
CTS_TEST(testGroup, "createPipeline,at_over").params([](ParamsBuilder u) { return kMaximumLimitBaseParams(u).combine("async", {false, true}).combine("bindingCombination", kBindingCombinationValues()).combine("access", storageTextureAccessValues()).filter([](const ParamRecord& p) { return storageTextureAccessAllowedInVisibility(getStageVisibilityForBindingCombination(valueAs<std::string>(*findParam(p, "bindingCombination"))), valueAs<std::string>(*findParam(p, "access"))); }).beginSubcases().combine("order", kReorderOrderValues()).combine("bindGroupTest", kBindGroupTestValues()); }).fn([](MaxStorageTexturesPerShaderStageTest& t) {
    const bool async = t.param<bool>("async"); const std::string combo = t.param<std::string>("bindingCombination"); const std::string access = t.param<std::string>("access"); const std::string bindGroupTest = t.param<std::string>("bindGroupTest"); const ReorderOrder order = parseReorderOrder(t.param<std::string>("order")); const std::string pipelineType = getPipelineTypeForBindingCombination(combo); const std::string limitTest = t.param<std::string>("limitTest");
    t.testDeviceWithRequestedMaximumLimits(limitTest, t.param<std::string>("testValueName"), [&](const MaximumLimitTestInputs& in) { WGPUCompatibilityModeLimits compat = WGPU_COMPATIBILITY_MODE_LIMITS_INIT; const WGPULimits limits = queryLimits(in.device, &compat); if (bindGroupTest == "sameGroup" && in.testValue > limits.maxBindingsPerBindGroup) t.skip("can not test bindings in same group"); const WGPUShaderStage visibility = getStageVisibilityForBindingCombination(combo); skipStorageTextures(t, visibility, in.testValue); const std::string wgslAccess = storageTextureWGSLAccess(access); const std::string code = getPerStageWGSLForBindingCombinationStorageTextures(combo, order, bindGroupTest, [&](int i, int j) { return "var u" + std::to_string(j) + "_" + std::to_string(i) + ": texture_storage_2d<r32float, " + wgslAccess + ">"; }, [&](int i, int j) { if (access == "write-only") return "textureStore(u" + std::to_string(j) + "_" + std::to_string(i) + ", vec2u(0), vec4f(0));"; return "_ = textureLoad(u" + std::to_string(j) + "_" + std::to_string(i) + ", vec2u(0));"; }, limits.maxBindGroups, in.testValue); WGPUShaderModule module = t.createShaderModuleTracked(code); t.testCreatePipeline(pipelineType, async, module, in.shouldError, code); }, extraLimits(t, limitTest));
});
} // namespace
