// Ported from gpuweb/cts src/webgpu/api/validation/capability_checks/limits/maxStorageBuffersPerShaderStage.spec.ts @ b507bd117e53db86f2fb52d0d858d3ae7d684a85
#include "cts/test.h"
#include "limit_utils.h"
using namespace cts; using namespace cts::capability_limits;
namespace {
class MaxStorageBuffersPerShaderStageTest : public LimitTest { public: const char* limitName() const override { return "maxStorageBuffersPerShaderStage"; } };
TestGroup<MaxStorageBuffersPerShaderStageTest> testGroup = MakeTestGroup<MaxStorageBuffersPerShaderStageTest>("api,validation,capability_checks,limits,maxStorageBuffersPerShaderStage", "API Validation Tests for maxStorageBuffersPerShaderStage.");
std::vector<LimitRequestEntry> extraLimits(MaxStorageBuffersPerShaderStageTest& t, std::string_view limitTest) { std::vector<LimitRequestEntry> v = {adapterLimitRequest("maxBindingsPerBindGroup"), adapterLimitRequest("maxBindGroups")}; addMaximumLimitUpToDependentLimit(t, v, "maxStorageBuffersInFragmentStage", "maxStorageBuffersPerShaderStage", limitTest); addMaximumLimitUpToDependentLimit(t, v, "maxStorageBuffersInVertexStage", "maxStorageBuffersPerShaderStage", limitTest); return v; }
CTS_TEST(testGroup, "createBindGroupLayout,at_over").params([](ParamsBuilder u) { return kMaximumLimitBaseParams(u).combine("visibility", shaderStageCombinationWithStageValues()).combine("type", storageBufferTypeValues()).combine("order", kReorderOrderValues()).filter([](const ParamRecord& p) { const auto visibility = static_cast<WGPUShaderStage>(valueAs<uint64_t>(*findParam(p, "visibility"))); const std::string type = valueAs<std::string>(*findParam(p, "type")); return (visibility & WGPUShaderStage_Vertex) == 0 || type != "storage"; }); }).fn([](MaxStorageBuffersPerShaderStageTest& t) {
    const auto visibility = static_cast<WGPUShaderStage>(t.param<uint64_t>("visibility")); const std::string type = t.param<std::string>("type"); const ReorderOrder order = parseReorderOrder(t.param<std::string>("order")); const std::string limitTest = t.param<std::string>("limitTest");
    t.testDeviceWithRequestedMaximumLimits(limitTest, t.param<std::string>("testValueName"), [&](const MaximumLimitTestInputs& in) { if (t.getAdapterLimit("maxBindingsPerBindGroup") < in.testValue) t.skip("maxBindingsPerBindGroup is less than test value"); t.skipIfNotEnoughStorageBuffersInStage(visibility, in.testValue); t.expectValidationErrorOnLimitDevice([&] { createPerStageBindGroupLayout(t, visibility, parseStorageBufferKind(type), order, in.testValue); }, in.shouldError); }, extraLimits(t, limitTest));
});
CTS_TEST(testGroup, "createPipelineLayout,at_over").params([](ParamsBuilder u) { return kMaximumLimitBaseParams(u).combine("visibility", shaderStageCombinationWithStageValues()).combine("type", storageBufferTypeValues()).combine("order", kReorderOrderValues()).filter([](const ParamRecord& p) { const auto visibility = static_cast<WGPUShaderStage>(valueAs<uint64_t>(*findParam(p, "visibility"))); const std::string type = valueAs<std::string>(*findParam(p, "type")); return (visibility & WGPUShaderStage_Vertex) == 0 || type != "storage"; }); }).fn([](MaxStorageBuffersPerShaderStageTest& t) {
    const auto visibility = static_cast<WGPUShaderStage>(t.param<uint64_t>("visibility")); const std::string type = t.param<std::string>("type"); const ReorderOrder order = parseReorderOrder(t.param<std::string>("order")); const std::string limitTest = t.param<std::string>("limitTest");
    t.testDeviceWithRequestedMaximumLimits(limitTest, t.param<std::string>("testValueName"), [&](const MaximumLimitTestInputs& in) { t.skipIfNotEnoughStorageBuffersInStage(visibility, in.testValue); testPerStageCreatePipelineLayout(t, visibility, parseStorageBufferKind(type), order, in); }, extraLimits(t, limitTest));
});
CTS_TEST(testGroup, "createPipeline,at_over").params([](ParamsBuilder u) { return kMaximumLimitBaseParams(u).combine("async", {false, true}).combine("bindingCombination", kBindingCombinationValues()).beginSubcases().combine("order", kReorderOrderValues()).combine("bindGroupTest", kBindGroupTestValues()); }).fn([](MaxStorageBuffersPerShaderStageTest& t) {
    const bool async = t.param<bool>("async"); const std::string combo = t.param<std::string>("bindingCombination"); const std::string bindGroupTest = t.param<std::string>("bindGroupTest"); const ReorderOrder order = parseReorderOrder(t.param<std::string>("order")); const std::string pipelineType = getPipelineTypeForBindingCombination(combo); const std::string limitTest = t.param<std::string>("limitTest");
    t.testDeviceWithRequestedMaximumLimits(limitTest, t.param<std::string>("testValueName"), [&](const MaximumLimitTestInputs& in) { WGPUCompatibilityModeLimits compat = WGPU_COMPATIBILITY_MODE_LIMITS_INIT; const WGPULimits limits = queryLimits(in.device, &compat); if (bindGroupTest == "sameGroup" && in.testValue > limits.maxBindingsPerBindGroup) t.skip("can not test bindings in same group"); const WGPUShaderStage visibility = getStageVisibilityForBindingCombination(combo); t.skipIfNotEnoughStorageBuffersInStage(visibility, in.testValue); const std::string code = getPerStageWGSLForBindingCombination(combo, order, bindGroupTest, [](int i, int j) { return "var<storage> u" + std::to_string(j) + "_" + std::to_string(i) + ": f32"; }, [](int i, int j) { return "_ = u" + std::to_string(j) + "_" + std::to_string(i) + ";"; }, limits.maxBindGroups, in.testValue); WGPUShaderModule module = t.createShaderModuleTracked(code); t.testCreatePipeline(pipelineType, async, module, in.shouldError, code); }, extraLimits(t, limitTest));
});
} // namespace
