// Ported from gpuweb/cts src/webgpu/api/operation/texture_view/texture_component_swizzle.spec.ts @ b507bd117e53db86f2fb52d0d858d3ae7d684a85
//
// Port notes / deviations:
// - Upstream computes the expected (pre-swizzle) source texel values fully on the
//   CPU: it fills the texture with random data generated by `texture_utils.ts`
//   (including a GPU sampling round-trip for compressed and unencodable depth
//   formats) and converts each texel to its RGBA "result format" with
//   convertPerTexelComponentToResultFormat. This port keeps the same shape but
//   obtains the source values with a small GPU pre-pass: the texture is filled
//   with deterministic pseudo-random data, then the 4 source texels are read back
//   through an *identity (non-swizzled)* view with textureLoad. This is
//   semantically equivalent (it handles decompression and depth quantization
//   exactly like upstream's readTextureToTexelViews) and keeps the swizzle itself
//   as the only thing under test. To preserve upstream's strictness about the
//   spec-mandated default components ([v, 0, 0, 1] for depth/stencil, missing
//   color components -> 0/0/1), the readback uses texture_depth_* types for
//   depth-only aspects and the CPU overwrites the components that are not present
//   in the source format with the spec defaults, exactly like
//   convertPerTexelComponentToResultFormat does.
// - Fill strategy per format class (upstream createTextureWithRandomDataAndGetTexelsForEachAspect):
//   encodable color formats -> queue.writeTexture with random (always-valid)
//   encodings; float-component formats encode in-range finite values via the
//   texel_data pack helpers to avoid NaN/Inf (mirrors upstream's +/-1000 limit);
//   compressed formats -> random block bytes (ASTC uses upstream's void-extent
//   block filler, so blocks are solid colors; the sample coordinate crosses a
//   block boundary exactly as upstream arranges); depth aspects -> rendered with
//   a frag_depth pattern (per-texel distinct values straddling depthRef=0.5);
//   stencil aspects -> writeTexture of random bytes (single-sampled) or a render
//   pass stencil clear to a constant (multisampled, where only one texel is read
//   by textureLoad anyway).
// - Upstream multisampled texture descriptors include COPY_DST; this port only
//   adds COPY_DST for single-sampled textures (multisampled fills go through a
//   render pass).
// - Compatibility-mode-only behaviors have no analog on these core native
//   backends and are omitted: t.isCompatibility skips (equal-swizzle requirement,
//   depth+non-comparison-sampler restriction, skipIfTextureLoadNotSupportedForTextureType)
//   and the expectValidationError branch for differing swizzles in compat.
// - Upstream caches pipelines per device (s_deviceToPipelines); this port creates
//   the (tracked) pipelines per subcase for lifetime safety.
// - Final comparison: upstream uses ttu.expectTexelViewComparisonIsOkInTexture
//   with maxFractionalDiff 0.01 on the rgba32{float,uint,sint} output texture.
//   The port copies the 2x1 output texture to a buffer and compares per
//   component: exact for integer result formats, |diff| <= 0.01 (or NaN==NaN)
//   for float result formats.

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <optional>
#include <sstream>
#include <string>
#include <string_view>
#include <vector>

#include "cts/gpu.h"
#include "cts/test.h"
#include "webgpu/texture_format.h"
#include "webgpu/util/enum_strings.h"
#include "webgpu/util/texel_data.h"
#include "webgpu/util/texture_layout.h"

using namespace cts;

namespace {

TestGroup<AllFeaturesMaxLimitsGpuTest> g = MakeTestGroup<AllFeaturesMaxLimitsGpuTest>(
    "api,operation,texture_view,texture_component_swizzle",
    "\n"
    "Operational tests for the 'texture-component-swizzle' feature.\n"
    "\n"
    "Test that:\n"
    "* when the feature is on, swizzling is applied correctly.\n"
    "\n"
    "Note: for texture_depth_xxx we only get f32\n"
    "What happens in the GPU (at least in Metal)\n"
    "\n"
    "  1. we start with [depthOrCompareResult, depthOrCompareResult, depthOrCompareResult, 1]\n"
    "  2. we then swizzle\n"
    "  3. we then read the RED channel\n"
    "\n"
    "Gather will do this 4 times and give us the result of step 3 in each channel.\n"
    "\n"
    "The WebGPU spec says we should be starting with [depthOrCompare, 0, 0, 1] and the\n"
    "implementation should deal with this.\n");

// kSwizzleTests from src/webgpu/api/validation/capability_checks/features/texture_component_swizzle_utils.ts
constexpr std::array<std::string_view, 19> kSwizzleTests = {{
    "rgba",
    "0000",
    "1111",
    "rrrr",
    "gggg",
    "bbbb",
    "aaaa",
    "abgr",
    "gbar",
    "barg",
    "argb",
    "0gba",
    "r0ba",
    "rg0a",
    "rgb0",
    "1gba",
    "r1ba",
    "rg1a",
    "rgb1",
}};

constexpr std::array<std::string_view, 9> kTextureBuiltinFunctions = {{
    "textureGather",
    "textureGatherCompare",
    "textureLoad",
    "textureSample",
    "textureSampleBias",
    "textureSampleCompare",
    "textureSampleCompareLevel",
    "textureSampleGrad",
    "textureSampleLevel",
    // 'textureSampleBaseClampToEdge',  // external textures don't have a view to swizzle.
}};

constexpr double kDepthRef = 0.5;
constexpr uint32_t kMultisampledStencilClearValue = 0xA5;

// ---------------------------------------------------------------------------
// Small generic helpers
// ---------------------------------------------------------------------------

WGPUStringView stringView(std::string_view value) {
    return WGPUStringView{value.data(), value.size()};
}

uint32_t alignTo(uint32_t value, uint32_t alignment) {
    return (value + alignment - 1) / alignment * alignment;
}

bool endsWith(std::string_view text, std::string_view suffix) {
    return text.size() >= suffix.size()
        && text.compare(text.size() - suffix.size(), suffix.size(), suffix) == 0;
}

// Deterministic hash for pseudo-random fill data (stand-in for upstream hashU32).
uint32_t hashU32(uint32_t a, uint32_t b = 0, uint32_t c = 0, uint32_t d = 0) {
    uint32_t x = a * 0x9E3779B9u + b * 0x85EBCA6Bu + c * 0xC2B2AE35u + d * 0x27D4EB2Fu + 0x165667B1u;
    x ^= x >> 16;
    x *= 0x7FEB352Du;
    x ^= x >> 15;
    x *= 0x846CA68Bu;
    x ^= x >> 16;
    return x;
}

double hash01(uint32_t a, uint32_t b = 0, uint32_t c = 0, uint32_t d = 0) {
    return static_cast<double>(hashU32(a, b, c, d)) / static_cast<double>(0xFFFFFFFFu);
}

// ---------------------------------------------------------------------------
// Param-time helpers (static format info only; no GPU access)
// ---------------------------------------------------------------------------

bool isBuiltinComparison(std::string_view func) {
    return func == "textureGatherCompare"
        || func == "textureSampleCompare"
        || func == "textureSampleCompareLevel";
}

bool isBuiltinGather(std::string_view func) {
    return func == "textureGather" || func == "textureGatherCompare";
}

bool canBuiltinTakeTextureDepth(std::string_view func) {
    return func == "textureGather"
        || func == "textureGatherCompare"
        || func == "textureLoad"
        || func == "textureSample"
        || func == "textureSampleCompare"
        || func == "textureSampleCompareLevel"
        || func == "textureSampleLevel";
}

bool isSingleChannelInput(std::string_view input) {
    return input == "texture_depth_2d" || input == "texture_depth_multisampled_2d";
}

bool isMultisampledInput(std::string_view input) {
    return input == "texture_multisampled_2d<f32>"
        || input == "texture_multisampled_2d<u32>"
        || input == "texture_multisampled_2d<i32>"
        || input == "texture_depth_multisampled_2d";
}

// isFillable: !isCompressedTextureFormat(format) || !format.endsWith('float').
bool isFillableFormatId(const std::string& formatId) {
    const WGPUTextureFormat format = parseTextureFormat(formatId);
    return !isCompressedTextureFormat(format) || !endsWith(formatId, "float");
}

// Upstream isSintOrUintFormat(effectiveFormat) where the effective format for the
// stencil-only aspect is 'stencil8' (whose type is uint).
bool isSintOrUintFormatId(const std::string& formatId) {
    if (formatId == "stencil8") {
        return true;
    }
    return endsWith(formatId, "uint") || endsWith(formatId, "sint");
}

bool isDepthFormatId(const std::string& formatId) {
    return textureFormatInfo(parseTextureFormat(formatId)).hasDepth;
}

bool isStencilFormatId(const std::string& formatId) {
    return textureFormatInfo(parseTextureFormat(formatId)).hasStencil;
}

// Upstream canUseBuiltinFuncWithFormat.
bool canUseBuiltinFuncWithFormatId(
    std::string_view func,
    const std::string& formatId,
    const std::string& aspectId) {
    const std::string effectiveFormat = aspectId == "stencil-only" ? std::string("stencil8") : formatId;
    if (isSintOrUintFormatId(effectiveFormat)) {
        return func == "textureGather" || func == "textureLoad";
    }
    if (!isDepthFormatId(effectiveFormat)) {
        return func != "textureGatherCompare"
            && func != "textureSampleCompare"
            && func != "textureSampleCompareLevel";
    }
    return true;
}

// getTextureFormatTypeInfo(format, aspect).componentType ('f32' | 'u32' | 'i32').
std::string componentTypeForFormatAspect(const std::string& formatId, const std::string& aspectId) {
    if (aspectId == "stencil-only") {
        return "u32";
    }
    if (aspectId == "depth-only") {
        return "f32";
    }
    if (endsWith(formatId, "uint")) {
        return "u32";
    }
    if (endsWith(formatId, "sint")) {
        return "i32";
    }
    return "f32";
}

// Upstream isTextureFormatPossiblyMultisampled.
bool isPossiblyMultisampledFormat(WGPUTextureFormat format) {
    return textureFormatInfo(format).multisample || isTier1BlendableMultisampleTextureFormat(format);
}

// ---------------------------------------------------------------------------
// Runtime helpers
// ---------------------------------------------------------------------------

// Formats whose color type is 'unfilterable-float' in upstream format_info.ts.
constexpr std::array<WGPUTextureFormat, 9> kUnfilterableFloatFormats = {
    WGPUTextureFormat_R16Unorm,
    WGPUTextureFormat_R16Snorm,
    WGPUTextureFormat_RG16Unorm,
    WGPUTextureFormat_RG16Snorm,
    WGPUTextureFormat_RGBA16Unorm,
    WGPUTextureFormat_RGBA16Snorm,
    WGPUTextureFormat_R32Float,
    WGPUTextureFormat_RG32Float,
    WGPUTextureFormat_RGBA32Float,
};

// getTextureFormatType(format, aspect) ('float' | 'unfilterable-float' | 'sint' | 'uint' | 'depth').
std::string formatTypeForFormatAspect(const std::string& formatId, const std::string& aspectId) {
    if (aspectId == "stencil-only") {
        return "uint";
    }
    if (aspectId == "depth-only") {
        return "depth";
    }
    if (endsWith(formatId, "uint")) {
        return "uint";
    }
    if (endsWith(formatId, "sint")) {
        return "sint";
    }
    if (textureFormatInList(parseTextureFormat(formatId), kUnfilterableFloatFormats)) {
        return "unfilterable-float";
    }
    return "float";
}

WGPUComponentSwizzle parseComponentSwizzle(char c) {
    switch (c) {
        case '0':
            return WGPUComponentSwizzle_Zero;
        case '1':
            return WGPUComponentSwizzle_One;
        case 'r':
            return WGPUComponentSwizzle_R;
        case 'g':
            return WGPUComponentSwizzle_G;
        case 'b':
            return WGPUComponentSwizzle_B;
        case 'a':
            return WGPUComponentSwizzle_A;
        default:
            std::abort();
    }
}

WGPUTextureComponentSwizzle makeSwizzle(const std::string& swizzle) {
    WGPUTextureComponentSwizzle out = WGPU_TEXTURE_COMPONENT_SWIZZLE_INIT;
    out.r = parseComponentSwizzle(swizzle[0]);
    out.g = parseComponentSwizzle(swizzle[1]);
    out.b = parseComponentSwizzle(swizzle[2]);
    out.a = parseComponentSwizzle(swizzle[3]);
    return out;
}

size_t swizzleIndex(const std::string& swizzle) {
    for (size_t i = 0; i < kSwizzleTests.size(); ++i) {
        if (kSwizzleTests[i] == swizzle) {
            return i;
        }
    }
    std::abort();
}

using Color = std::array<double, 4>;

// Upstream swizzleTexel.
Color swizzleTexel(const Color& src, const std::string& swizzle) {
    Color out = {0.0, 0.0, 0.0, 0.0};
    for (size_t i = 0; i < 4; ++i) {
        switch (swizzle[i]) {
            case '0':
                out[i] = 0.0;
                break;
            case '1':
                out[i] = 1.0;
                break;
            case 'r':
                out[i] = src[0];
                break;
            case 'g':
                out[i] = src[1];
                break;
            case 'b':
                out[i] = src[2];
                break;
            case 'a':
                out[i] = src[3];
                break;
            default:
                std::abort();
        }
    }
    return out;
}

// Upstream applyCompareToTexel with components [R, G, B, A]: the comparison
// applies to R; G/B default to 0 and A defaults to 1.
Color applyCompareToTexel(const Color& src, const std::string& compare, double ref) {
    bool pass = false;
    if (compare == "less") {
        pass = ref < src[0];
    } else if (compare == "greater") {
        pass = ref > src[0];
    } else {
        std::abort();
    }
    return Color{pass ? 1.0 : 0.0, 0.0, 0.0, 1.0};
}

// Upstream gather():
//   texel gather offsets
// r [0, 1] 2
// g [1, 1] 3
// b [1, 0] 1
// a [0, 0] 0
Color gather(const std::array<Color, 4>& srcColors, int channel) {
    return Color{
        srcColors[2][static_cast<size_t>(channel)],
        srcColors[3][static_cast<size_t>(channel)],
        srcColors[1][static_cast<size_t>(channel)],
        srcColors[0][static_cast<size_t>(channel)],
    };
}

// ---------------------------------------------------------------------------
// Texture fill (stand-in for upstream createTextureWithRandomDataAndGetTexels...)
// ---------------------------------------------------------------------------

// Fill a single-sampled encodable color texture with deterministic pseudo-random
// data via queue.writeTexture. Formats with float components are encoded from
// in-range finite values (upstream limits float ranges to +/-1000); all other
// formats accept arbitrary bytes as valid encodings (incl. rgb9e5ufloat, which
// cannot encode NaN/Inf).
void fillEncodableColorTexture(
    AllFeaturesMaxLimitsGpuTest& t,
    WGPUTexture texture,
    WGPUTextureFormat format,
    uint32_t width,
    uint32_t height) {
    const TexelRepresentation& rep = texelRepresentation(format);
    bool hasFloatComponents = false;
    for (TexelComponent component : rep.componentOrder) {
        const ComponentDataType type = rep.dataTypes[static_cast<size_t>(component)];
        if (type == ComponentDataType::Float || type == ComponentDataType::Ufloat) {
            hasFloatComponents = true;
        }
    }
    // rgb9e5ufloat numberToBits is unimplemented in texel_data; raw random bytes
    // are always valid (finite) encodings for it.
    const bool useColorsPath = hasFloatComponents && format != WGPUTextureFormat_RGB9E5Ufloat;

    std::vector<uint8_t> data;
    data.reserve(static_cast<size_t>(width) * height * rep.bytesPerBlock);
    for (uint32_t y = 0; y < height; ++y) {
        for (uint32_t x = 0; x < width; ++x) {
            if (useColorsPath) {
                TexelComponents texel;
                for (TexelComponent component : rep.componentOrder) {
                    const size_t index = static_cast<size_t>(component);
                    const double r01 = hash01(x, y, static_cast<uint32_t>(index), static_cast<uint32_t>(format));
                    const ComponentDataType type = rep.dataTypes[index];
                    double value = 0.0;
                    if (type == ComponentDataType::Float) {
                        value = -1000.0 + r01 * 2000.0;
                    } else if (type == ComponentDataType::Ufloat) {
                        value = r01 * 1000.0;
                    } else {
                        value = r01;
                    }
                    texel.values[index] = value;
                }
                const std::vector<uint8_t> texelBytes = rep.packBits(rep.numberToBits(texel));
                data.insert(data.end(), texelBytes.begin(), texelBytes.end());
            } else {
                for (uint32_t b = 0; b < rep.bytesPerBlock; ++b) {
                    data.push_back(static_cast<uint8_t>(hashU32(x, y, b, static_cast<uint32_t>(format))));
                }
            }
        }
    }

    WGPUTexelCopyBufferLayout layout = WGPU_TEXEL_COPY_BUFFER_LAYOUT_INIT;
    layout.offset = 0;
    layout.bytesPerRow = width * rep.bytesPerBlock;
    layout.rowsPerImage = height;
    t.queueWriteTexture(texture, WGPUExtent3D{width, height, 1}, layout, data.data(), data.size());
}

// Fill a compressed texture with random block data. ASTC blocks use upstream's
// void-extent (solid color) block filler; BC/ETC2/EAC accept arbitrary bytes.
void fillCompressedTexture(
    AllFeaturesMaxLimitsGpuTest& t,
    WGPUTexture texture,
    WGPUTextureFormat format,
    uint32_t width,
    uint32_t height) {
    const TextureBlockInfo info = getBlockInfoForTextureFormat(format);
    const uint32_t blocksAcross = (width + info.blockWidth - 1) / info.blockWidth;
    const uint32_t blocksDown = (height + info.blockHeight - 1) / info.blockHeight;
    const uint32_t bytesPerRow = blocksAcross * info.bytesPerBlock;
    const bool astc = isASTCTextureFormat(format);

    std::vector<uint8_t> data(static_cast<size_t>(bytesPerRow) * blocksDown);
    for (uint32_t by = 0; by < blocksDown; ++by) {
        for (uint32_t bx = 0; bx < blocksAcross; ++bx) {
            const size_t offset = static_cast<size_t>(by) * bytesPerRow + static_cast<size_t>(bx) * info.bytesPerBlock;
            uint32_t b = 0;
            if (astc) {
                // Upstream makeAstcBlockFiller: void-extent header, random color bits.
                const std::array<uint8_t, 8> header = {{0xFC, 0xFD, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF}};
                for (; b < header.size(); ++b) {
                    data[offset + b] = header[b];
                }
            }
            for (; b < info.bytesPerBlock; ++b) {
                data[offset + b] = static_cast<uint8_t>(hashU32(bx, by, b, static_cast<uint32_t>(format)));
            }
        }
    }

    WGPUTexelCopyBufferLayout layout = WGPU_TEXEL_COPY_BUFFER_LAYOUT_INIT;
    layout.offset = 0;
    layout.bytesPerRow = bytesPerRow;
    layout.rowsPerImage = blocksDown;
    t.queueWriteTexture(texture, WGPUExtent3D{width, height, 1}, layout, data.data(), data.size());
}

// Fill the stencil aspect of a single-sampled texture with random bytes.
void fillStencilAspectViaWrite(
    AllFeaturesMaxLimitsGpuTest& t,
    WGPUTexture texture,
    uint32_t width,
    uint32_t height) {
    std::vector<uint8_t> data(static_cast<size_t>(width) * height);
    for (uint32_t y = 0; y < height; ++y) {
        for (uint32_t x = 0; x < width; ++x) {
            data[static_cast<size_t>(y) * width + x] = static_cast<uint8_t>(hashU32(x, y, 0x57u));
        }
    }

    WGPUTexelCopyTextureInfo destination = WGPU_TEXEL_COPY_TEXTURE_INFO_INIT;
    destination.texture = texture;
    destination.mipLevel = 0;
    destination.origin = WGPUOrigin3D{0, 0, 0};
    destination.aspect = WGPUTextureAspect_StencilOnly;

    WGPUTexelCopyBufferLayout layout = WGPU_TEXEL_COPY_BUFFER_LAYOUT_INIT;
    layout.offset = 0;
    layout.bytesPerRow = width;
    layout.rowsPerImage = height;

    const WGPUExtent3D copySize{width, height, 1};
    wgpuQueueWriteTexture(t.queue(), &destination, data.data(), data.size(), &layout, &copySize);
}

// frag_depth pattern used by fillDepthViaRender below. Values are distinct per
// texel within any 2x2 region, straddle kDepthRef (0.5), and never equal it.
constexpr std::string_view kDepthPatternWGSL =
    "(f32((xy.x * 7u + xy.y * 13u) % 16u) + 0.5) / 16.0";

// Render pseudo-random depth values into the depth aspect (and, for
// depth+stencil formats, load (single-sampled) or clear-to-constant
// (multisampled) the stencil aspect).
void fillDepthViaRender(
    AllFeaturesMaxLimitsGpuTest& t,
    WGPUTexture texture,
    WGPUTextureFormat format,
    bool hasStencil,
    bool multisampled) {
    std::ostringstream wgsl;
    wgsl << "@vertex fn vs(@builtin(vertex_index) vi: u32) -> @builtin(position) vec4f {\n"
            "  var pos = array<vec2<f32>, 3>(vec2f(-1.0, -1.0), vec2f(3.0, -1.0), vec2f(-1.0, 3.0));\n"
            "  return vec4f(pos[vi], 0.0, 1.0);\n"
            "}\n"
            "@fragment fn fs(@builtin(position) pos: vec4f) -> @builtin(frag_depth) f32 {\n"
            "  let xy = vec2u(pos.xy);\n"
            "  return "
         << kDepthPatternWGSL
         << ";\n"
            "}\n";
    WGPUShaderModule module = t.createShaderModuleTracked(wgsl.str());

    WGPUDepthStencilState depthStencil = WGPU_DEPTH_STENCIL_STATE_INIT;
    depthStencil.format = format;
    depthStencil.depthWriteEnabled = WGPUOptionalBool_True;
    depthStencil.depthCompare = WGPUCompareFunction_Always;

    WGPUFragmentState fragment = WGPU_FRAGMENT_STATE_INIT;
    fragment.module = module;
    fragment.entryPoint = stringView("fs");
    fragment.targetCount = 0;
    fragment.targets = nullptr;

    WGPURenderPipelineDescriptor pipelineDesc = WGPU_RENDER_PIPELINE_DESCRIPTOR_INIT;
    pipelineDesc.layout = nullptr; // 'auto'
    pipelineDesc.vertex.module = module;
    pipelineDesc.vertex.entryPoint = stringView("vs");
    pipelineDesc.primitive.topology = WGPUPrimitiveTopology_TriangleList;
    pipelineDesc.depthStencil = &depthStencil;
    pipelineDesc.multisample.count = multisampled ? 4 : 1;
    pipelineDesc.fragment = &fragment;
    WGPURenderPipeline pipeline = t.createRenderPipelineTracked(pipelineDesc);

    WGPUTextureViewDescriptor viewDesc = WGPU_TEXTURE_VIEW_DESCRIPTOR_INIT;
    WGPUTextureView view = t.createViewTracked(texture, viewDesc);

    WGPURenderPassDepthStencilAttachment dsAttachment = WGPU_RENDER_PASS_DEPTH_STENCIL_ATTACHMENT_INIT;
    dsAttachment.view = view;
    dsAttachment.depthLoadOp = WGPULoadOp_Clear;
    dsAttachment.depthClearValue = 0.0f;
    dsAttachment.depthStoreOp = WGPUStoreOp_Store;
    if (hasStencil) {
        dsAttachment.stencilLoadOp = multisampled ? WGPULoadOp_Clear : WGPULoadOp_Load;
        dsAttachment.stencilClearValue = kMultisampledStencilClearValue;
        dsAttachment.stencilStoreOp = WGPUStoreOp_Store;
    }

    WGPURenderPassDescriptor passDesc = WGPU_RENDER_PASS_DESCRIPTOR_INIT;
    passDesc.colorAttachmentCount = 0;
    passDesc.colorAttachments = nullptr;
    passDesc.depthStencilAttachment = &dsAttachment;

    WGPUCommandEncoder encoder = t.createCommandEncoderTracked();
    WGPURenderPassEncoder pass = wgpuCommandEncoderBeginRenderPass(encoder, &passDesc);
    wgpuRenderPassEncoderSetPipeline(pass, pipeline);
    wgpuRenderPassEncoderDraw(pass, 3, 1, 0, 0);
    wgpuRenderPassEncoderEnd(pass);
    WGPUCommandBuffer commandBuffer = t.finishTracked(encoder);
    wgpuQueueSubmit(t.queue(), 1, &commandBuffer);
}

// Multisampled stencil-only (stencil8) textures cannot be written with
// writeTexture; clear the stencil aspect to a constant via a render pass.
// (Only one texel is ever read from multisampled textures - textureLoad at the
// sample coordinate - so a constant value is sufficient.)
void clearStencilViaPass(AllFeaturesMaxLimitsGpuTest& t, WGPUTexture texture) {
    WGPUTextureViewDescriptor viewDesc = WGPU_TEXTURE_VIEW_DESCRIPTOR_INIT;
    WGPUTextureView view = t.createViewTracked(texture, viewDesc);

    WGPURenderPassDepthStencilAttachment dsAttachment = WGPU_RENDER_PASS_DEPTH_STENCIL_ATTACHMENT_INIT;
    dsAttachment.view = view;
    dsAttachment.stencilLoadOp = WGPULoadOp_Clear;
    dsAttachment.stencilClearValue = kMultisampledStencilClearValue;
    dsAttachment.stencilStoreOp = WGPUStoreOp_Store;

    WGPURenderPassDescriptor passDesc = WGPU_RENDER_PASS_DESCRIPTOR_INIT;
    passDesc.colorAttachmentCount = 0;
    passDesc.colorAttachments = nullptr;
    passDesc.depthStencilAttachment = &dsAttachment;

    WGPUCommandEncoder encoder = t.createCommandEncoderTracked();
    WGPURenderPassEncoder pass = wgpuCommandEncoderBeginRenderPass(encoder, &passDesc);
    wgpuRenderPassEncoderEnd(pass);
    WGPUCommandBuffer commandBuffer = t.finishTracked(encoder);
    wgpuQueueSubmit(t.queue(), 1, &commandBuffer);
}

// Fill a multisampled color texture by rendering per-pixel values (all samples
// of a pixel get the same value; only sample 0 is read via textureLoad).
void fillMultisampledColorViaRender(
    AllFeaturesMaxLimitsGpuTest& t,
    WGPUTexture texture,
    WGPUTextureFormat format,
    const std::string& componentType) {
    std::ostringstream wgsl;
    wgsl << "@vertex fn vs(@builtin(vertex_index) vi: u32) -> @builtin(position) vec4f {\n"
            "  var pos = array<vec2<f32>, 3>(vec2f(-1.0, -1.0), vec2f(3.0, -1.0), vec2f(-1.0, 3.0));\n"
            "  return vec4f(pos[vi], 0.0, 1.0);\n"
            "}\n";
    if (componentType == "u32") {
        wgsl << "@fragment fn fs(@builtin(position) pos: vec4f) -> @location(0) vec4u {\n"
                "  let base = vec2u(pos.xy).x * 3u + vec2u(pos.xy).y * 5u;\n"
                "  return vec4u(base % 4u, (base + 1u) % 4u, (base + 2u) % 4u, (base + 3u) % 4u);\n"
                "}\n";
    } else if (componentType == "i32") {
        wgsl << "@fragment fn fs(@builtin(position) pos: vec4f) -> @location(0) vec4i {\n"
                "  let base = vec2u(pos.xy).x * 3u + vec2u(pos.xy).y * 5u;\n"
                "  return vec4i(i32(base % 5u) - 2, i32((base + 3u) % 5u) - 2,\n"
                "               i32((base + 6u) % 5u) - 2, i32((base + 9u) % 5u) - 2);\n"
                "}\n";
    } else {
        wgsl << "@fragment fn fs(@builtin(position) pos: vec4f) -> @location(0) vec4f {\n"
                "  let base = vec2u(pos.xy).x * 3u + vec2u(pos.xy).y * 5u;\n"
                "  return vec4f(f32(base % 9u) / 8.0, f32((base + 7u) % 9u) / 8.0,\n"
                "               f32((base + 14u) % 9u) / 8.0, f32((base + 21u) % 9u) / 8.0);\n"
                "}\n";
    }
    WGPUShaderModule module = t.createShaderModuleTracked(wgsl.str());

    WGPUColorTargetState colorTarget = WGPU_COLOR_TARGET_STATE_INIT;
    colorTarget.format = format;

    WGPUFragmentState fragment = WGPU_FRAGMENT_STATE_INIT;
    fragment.module = module;
    fragment.entryPoint = stringView("fs");
    fragment.targetCount = 1;
    fragment.targets = &colorTarget;

    WGPURenderPipelineDescriptor pipelineDesc = WGPU_RENDER_PIPELINE_DESCRIPTOR_INIT;
    pipelineDesc.layout = nullptr; // 'auto'
    pipelineDesc.vertex.module = module;
    pipelineDesc.vertex.entryPoint = stringView("vs");
    pipelineDesc.primitive.topology = WGPUPrimitiveTopology_TriangleList;
    pipelineDesc.multisample.count = 4;
    pipelineDesc.fragment = &fragment;
    WGPURenderPipeline pipeline = t.createRenderPipelineTracked(pipelineDesc);

    WGPUTextureViewDescriptor viewDesc = WGPU_TEXTURE_VIEW_DESCRIPTOR_INIT;
    WGPUTextureView view = t.createViewTracked(texture, viewDesc);

    WGPURenderPassColorAttachment colorAttachment = WGPU_RENDER_PASS_COLOR_ATTACHMENT_INIT;
    colorAttachment.view = view;
    colorAttachment.loadOp = WGPULoadOp_Clear;
    colorAttachment.storeOp = WGPUStoreOp_Store;
    colorAttachment.clearValue = WGPUColor{0.0, 0.0, 0.0, 0.0};

    WGPURenderPassDescriptor passDesc = WGPU_RENDER_PASS_DESCRIPTOR_INIT;
    passDesc.colorAttachmentCount = 1;
    passDesc.colorAttachments = &colorAttachment;

    WGPUCommandEncoder encoder = t.createCommandEncoderTracked();
    WGPURenderPassEncoder pass = wgpuCommandEncoderBeginRenderPass(encoder, &passDesc);
    wgpuRenderPassEncoderSetPipeline(pass, pipeline);
    wgpuRenderPassEncoderDraw(pass, 3, 1, 0, 0);
    wgpuRenderPassEncoderEnd(pass);
    WGPUCommandBuffer commandBuffer = t.finishTracked(encoder);
    wgpuQueueSubmit(t.queue(), 1, &commandBuffer);
}

// ---------------------------------------------------------------------------
// Source texel readback (stand-in for upstream's CPU-side texel views; see the
// port notes at the top of the file)
// ---------------------------------------------------------------------------

// Reads the 4 source texels at (x0, y0)..(x0+1, y0+1) through an identity
// (non-swizzled) view in their RGBA result-format representation, mirroring
// upstream convertPerTexelComponentToResultFormat: depth/stencil aspects yield
// [v, 0, 0, 1]; components missing from a (non-compressed) color format are
// replaced with the spec defaults (0 for G/B, 1 for A).
std::array<Color, 4> readSourceTexels(
    AllFeaturesMaxLimitsGpuTest& t,
    WGPUTexture texture,
    WGPUTextureFormat format,
    const std::string& aspectId,
    bool multisampled,
    const std::string& componentType,
    uint32_t x0,
    uint32_t y0) {
    const bool depthAspect = aspectId == "depth-only";
    const bool stencilAspect = aspectId == "stencil-only";

    std::string textureType;
    if (depthAspect) {
        textureType = multisampled ? "texture_depth_multisampled_2d" : "texture_depth_2d";
    } else if (multisampled) {
        textureType = "texture_multisampled_2d<" + componentType + ">";
    } else {
        textureType = "texture_2d<" + componentType + ">";
    }
    const std::string vecType =
        componentType == "u32" ? "vec4u" : componentType == "i32" ? "vec4i" : "vec4f";

    std::ostringstream wgsl;
    wgsl << "@group(0) @binding(0) var tex: " << textureType << ";\n"
         << "@group(0) @binding(1) var<storage, read_write> result: array<" << vecType << ", 4>;\n"
         << "@compute @workgroup_size(1) fn cs() {\n";
    for (uint32_t i = 0; i < 4; ++i) {
        const uint32_t x = x0 + (i % 2);
        const uint32_t y = y0 + (i / 2);
        wgsl << "  result[" << i << "] = ";
        if (depthAspect) {
            wgsl << "vec4f(textureLoad(tex, vec2u(" << x << ", " << y << "), 0), 0.0, 0.0, 1.0)";
        } else {
            wgsl << "textureLoad(tex, vec2u(" << x << ", " << y << "), 0)";
        }
        wgsl << ";\n";
    }
    wgsl << "}\n";
    WGPUShaderModule module = t.createShaderModuleTracked(wgsl.str());

    WGPUComputePipelineDescriptor pipelineDesc = WGPU_COMPUTE_PIPELINE_DESCRIPTOR_INIT;
    pipelineDesc.layout = nullptr; // 'auto'
    pipelineDesc.compute.module = module;
    pipelineDesc.compute.entryPoint = stringView("cs");
    WGPUComputePipeline pipeline = t.createComputePipelineTracked(pipelineDesc);

    WGPUTextureViewDescriptor viewDesc = WGPU_TEXTURE_VIEW_DESCRIPTOR_INIT;
    viewDesc.aspect = parseTextureAspect(aspectId);
    WGPUTextureView view = t.createViewTracked(texture, viewDesc);

    // Output buffer is created zero-filled (never pre-filled with expected values).
    WGPUBufferDescriptor bufferDesc = WGPU_BUFFER_DESCRIPTOR_INIT;
    bufferDesc.size = 64;
    bufferDesc.usage = WGPUBufferUsage_Storage | WGPUBufferUsage_CopySrc;
    WGPUBuffer resultBuffer = t.createBufferTracked(bufferDesc);

    // getBindGroupLayout is a getter -> must be released manually.
    WGPUBindGroupLayout bindGroupLayout = wgpuComputePipelineGetBindGroupLayout(pipeline, 0);
    std::array<WGPUBindGroupEntry, 2> entries = {{
        WGPU_BIND_GROUP_ENTRY_INIT,
        WGPU_BIND_GROUP_ENTRY_INIT,
    }};
    entries[0].binding = 0;
    entries[0].textureView = view;
    entries[1].binding = 1;
    entries[1].buffer = resultBuffer;

    WGPUBindGroupDescriptor bindGroupDesc = WGPU_BIND_GROUP_DESCRIPTOR_INIT;
    bindGroupDesc.layout = bindGroupLayout;
    bindGroupDesc.entryCount = entries.size();
    bindGroupDesc.entries = entries.data();
    WGPUBindGroup bindGroup = t.createBindGroupTracked(bindGroupDesc);
    wgpuBindGroupLayoutRelease(bindGroupLayout);

    WGPUCommandEncoder encoder = t.createCommandEncoderTracked();
    WGPUComputePassDescriptor passDesc = WGPU_COMPUTE_PASS_DESCRIPTOR_INIT;
    WGPUComputePassEncoder pass = wgpuCommandEncoderBeginComputePass(encoder, &passDesc);
    wgpuComputePassEncoderSetPipeline(pass, pipeline);
    wgpuComputePassEncoderSetBindGroup(pass, 0, bindGroup, 0, nullptr);
    wgpuComputePassEncoderDispatchWorkgroups(pass, 1, 1, 1);
    wgpuComputePassEncoderEnd(pass);
    WGPUCommandBuffer commandBuffer = t.finishTracked(encoder);
    wgpuQueueSubmit(t.queue(), 1, &commandBuffer);

    std::array<uint8_t, 64> raw = {};
    t.expectGPUBufferValuesPassCheck(
        resultBuffer,
        [&raw](const uint8_t* actual, size_t len) -> std::optional<std::string> {
            if (len < raw.size()) {
                return std::string("source texel readback too short");
            }
            std::memcpy(raw.data(), actual, raw.size());
            return std::nullopt;
        },
        0,
        raw.size());

    // Which components exist in the source format (upstream
    // convertPerTexelComponentToResultFormat uses the format's componentOrder for
    // encodable formats and all of RGBA for non-encodable, i.e. compressed, ones).
    std::array<bool, 4> present = {true, true, true, true};
    if (aspectId == "all" && !isCompressedTextureFormat(format)) {
        present = {false, false, false, false};
        for (TexelComponent component : texelRepresentation(format).componentOrder) {
            present[static_cast<size_t>(component)] = true;
        }
    }

    std::array<Color, 4> colors = {};
    for (size_t i = 0; i < 4; ++i) {
        Color c = {0.0, 0.0, 0.0, 0.0};
        for (size_t ch = 0; ch < 4; ++ch) {
            const uint8_t* bytes = raw.data() + i * 16 + ch * 4;
            if (componentType == "u32") {
                uint32_t v = 0;
                std::memcpy(&v, bytes, sizeof(v));
                c[ch] = static_cast<double>(v);
            } else if (componentType == "i32") {
                int32_t v = 0;
                std::memcpy(&v, bytes, sizeof(v));
                c[ch] = static_cast<double>(v);
            } else {
                float v = 0.0f;
                std::memcpy(&v, bytes, sizeof(v));
                c[ch] = static_cast<double>(v);
            }
        }
        if (stencilAspect) {
            c = Color{c[0], 0.0, 0.0, 1.0};
        } else if (!depthAspect) {
            for (size_t ch = 0; ch < 4; ++ch) {
                if (!present[ch]) {
                    c[ch] = ch == 3 ? 1.0 : 0.0;
                }
            }
        }
        colors[i] = c;
    }
    return colors;
}

// ---------------------------------------------------------------------------
// The test
// ---------------------------------------------------------------------------

std::string loadWGSL(const std::string& func, const std::string& input, int channel, int v) {
    std::ostringstream out;
    const std::string tex = "tex" + std::to_string(v);
    if (func == "textureGather") {
        if (isSingleChannelInput(input)) {
            out << "textureGather(" << tex << ", smp, uni.texCoord)";
        } else {
            out << "textureGather(" << channel << ", " << tex << ", smp, uni.texCoord)";
        }
    } else if (func == "textureGatherCompare") {
        out << "textureGatherCompare(" << tex << ", smp, uni.texCoord, 0.5)";
    } else if (func == "textureLoad") {
        out << "textureLoad(" << tex << ", vec2u(uni.texCoord * vec2f(textureDimensions(" << tex << "))), 0)";
    } else if (func == "textureSample") {
        out << "textureSample(" << tex << ", smp, uni.texCoord)";
    } else if (func == "textureSampleBias") {
        out << "textureSampleBias(" << tex << ", smp, uni.texCoord, 0)";
    } else if (func == "textureSampleCompare") {
        out << "textureSampleCompare(" << tex << ", smp, uni.texCoord, 0.5)";
    } else if (func == "textureSampleCompareLevel") {
        out << "textureSampleCompareLevel(" << tex << ", smp, uni.texCoord, 0.5)";
    } else if (func == "textureSampleGrad") {
        out << "textureSampleGrad(" << tex << ", smp, uni.texCoord, vec2f(0), vec2f(0))";
    } else if (func == "textureSampleLevel") {
        out << "textureSampleLevel(" << tex << ", smp, uni.texCoord, 0)";
    } else {
        std::abort();
    }
    return out.str();
}

CTS_TEST(g, "read_swizzle")
    .desc(
        "\n"
        "  Test reading textures with swizzles.\n"
        "  * Test that multiple swizzles of the same texture work.\n"
        "  * Test that multiple swizzles of the same fails in compat if the swizzles are different.\n"
        "  ")
    .params([](ParamsBuilder u) {
        std::vector<Value> formatValues;
        for (WGPUTextureFormat format : kAllTextureFormats) {
            formatValues.emplace_back(std::string(textureFormatIdentifier(format)));
        }
        std::vector<Value> funcValues;
        for (std::string_view func : kTextureBuiltinFunctions) {
            funcValues.emplace_back(std::string(func));
        }
        std::vector<Value> swizzleValues;
        for (std::string_view swizzle : kSwizzleTests) {
            swizzleValues.emplace_back(std::string(swizzle));
        }
        return u.combine("format", formatValues)
            .filter([](const ParamRecord& p) {
                return isFillableFormatId(valueAs<std::string>(*findParam(p, "format")));
            })
            .combine("func", funcValues)
            .beginSubcases()
            .expand("compare",
                    [](const ParamRecord& p) {
                        const std::string func = valueAs<std::string>(*findParam(p, "func"));
                        if (isBuiltinComparison(func)) {
                            return std::vector<Value>{Value("less"), Value("greater")};
                        }
                        return std::vector<Value>{Value("always")};
                    })
            .expand("aspect",
                    [](const ParamRecord& p) {
                        const std::string formatId = valueAs<std::string>(*findParam(p, "format"));
                        std::vector<Value> values;
                        if (isDepthFormatId(formatId) || isStencilFormatId(formatId)) {
                            if (isDepthFormatId(formatId)) {
                                values.emplace_back("depth-only");
                            }
                            if (isStencilFormatId(formatId)) {
                                values.emplace_back("stencil-only");
                            }
                        } else {
                            values.emplace_back("all");
                        }
                        return values;
                    })
            .filter([](const ParamRecord& p) {
                const std::string func = valueAs<std::string>(*findParam(p, "func"));
                const std::string formatId = valueAs<std::string>(*findParam(p, "format"));
                const std::string aspectId = valueAs<std::string>(*findParam(p, "aspect"));
                return canUseBuiltinFuncWithFormatId(func, formatId, aspectId);
            })
            .expand("input",
                    [](const ParamRecord& p) {
                        const std::string func = valueAs<std::string>(*findParam(p, "func"));
                        const std::string formatId = valueAs<std::string>(*findParam(p, "format"));
                        const std::string aspectId = valueAs<std::string>(*findParam(p, "aspect"));
                        std::vector<Value> values;
                        if (!isBuiltinComparison(func)) {
                            const std::string componentType = componentTypeForFormatAspect(formatId, aspectId);
                            values.emplace_back("texture_2d<" + componentType + ">");
                        }
                        if (isDepthFormatId(formatId) && canBuiltinTakeTextureDepth(func)
                            && aspectId == "depth-only") {
                            values.emplace_back("texture_depth_2d");
                        }
                        if (func == "textureLoad"
                            && isPossiblyMultisampledFormat(parseTextureFormat(formatId))) {
                            const std::string componentType = componentTypeForFormatAspect(formatId, aspectId);
                            values.emplace_back("texture_multisampled_2d<" + componentType + ">");
                            if (isDepthFormatId(formatId) && canBuiltinTakeTextureDepth(func)
                                && aspectId == "depth-only") {
                                values.emplace_back("texture_depth_multisampled_2d");
                            }
                        }
                        return values;
                    })
            .expand("channel",
                    [](const ParamRecord& p) {
                        const std::string func = valueAs<std::string>(*findParam(p, "func"));
                        const std::string input = valueAs<std::string>(*findParam(p, "input"));
                        if (func == "textureGather" && !isSingleChannelInput(input)) {
                            return std::vector<Value>{0, 1, 2, 3};
                        }
                        return std::vector<Value>{0};
                    })
            .combine("swizzle", swizzleValues)
            // used to choose a different 2nd swizzle. 0 = same swizzle as 1st
            .combine("otherSwizzleIndexOffset", {0, 1, 5});
    })
    .fn([](AllFeaturesMaxLimitsGpuTest& t) {
        if (!wgpuDeviceHasFeature(t.device(), WGPUFeatureName_TextureComponentSwizzle)) {
            t.skip("texture-component-swizzle feature is not supported");
        }
        const std::string formatId = t.param<std::string>("format");
        const WGPUTextureFormat format = parseTextureFormat(formatId);
        const std::string func = t.param<std::string>("func");
        const int channel = t.param<int>("channel");
        const std::string compare = t.param<std::string>("compare");
        const std::string aspectId = t.param<std::string>("aspect");
        const std::string input = t.param<std::string>("input");
        const std::string swizzle = t.param<std::string>("swizzle");
        const int otherSwizzleIndexOffset = t.param<int>("otherSwizzleIndexOffset");

        t.skipIfTextureFormatNotSupported(format);
        // Upstream skipIfTextureLoadNotSupportedForTextureType is a
        // compatibility-mode-only restriction; no analog on core backends.
        const bool multisampled = isMultisampledInput(input);
        if (multisampled && !t.isTextureFormatMultisampled(format)) {
            t.skip("format does not support multisampling on this device");
        }
        const std::string otherSwizzle = std::string(
            kSwizzleTests[(swizzleIndex(swizzle) + static_cast<size_t>(otherSwizzleIndexOffset))
                          % kSwizzleTests.size()]);

        const bool comparison = isBuiltinComparison(func);
        const bool singleChannel = isSingleChannelInput(input);

        // chooseTextureSize({ minSize: 2, minBlocks: 2, format })
        const TextureBlockInfo block = getBlockInfoForTextureFormat(format);
        const uint32_t width = alignTo(std::max(2u, block.blockWidth * 2u), block.blockWidth);
        const uint32_t height = alignTo(std::max(2u, block.blockHeight * 2u), block.blockHeight);
        // Choose a texture coordinate that will cross a block boundary for gather.
        const double tx = static_cast<double>(block.blockWidth) - 0.4;
        const double ty = static_cast<double>(block.blockHeight) - 0.4;
        const uint32_t x0 = static_cast<uint32_t>(tx);
        const uint32_t y0 = static_cast<uint32_t>(ty);

        // Create and fill the source texture.
        WGPUTextureDescriptor textureDesc = WGPU_TEXTURE_DESCRIPTOR_INIT;
        textureDesc.label = stringView("swizzle test texture");
        textureDesc.format = format;
        textureDesc.size = WGPUExtent3D{width, height, 1};
        textureDesc.sampleCount = multisampled ? 4 : 1;
        textureDesc.usage = WGPUTextureUsage_TextureBinding
            | (multisampled ? WGPUTextureUsage_None : WGPUTextureUsage_CopyDst)
            | (t.isTextureFormatUsableAsRenderAttachment(format) ? WGPUTextureUsage_RenderAttachment
                                                                 : WGPUTextureUsage_None);
        WGPUTexture texture = t.createTextureTracked(textureDesc);

        if (isDepthOrStencilTextureFormat(format)) {
            const bool hasDepth = isDepthTextureFormat(format);
            const bool hasStencil = isStencilTextureFormat(format);
            if (hasStencil && !multisampled) {
                fillStencilAspectViaWrite(t, texture, width, height);
            }
            if (hasDepth) {
                fillDepthViaRender(t, texture, format, hasStencil, multisampled);
            } else if (multisampled) {
                clearStencilViaPass(t, texture);
            }
        } else if (isCompressedTextureFormat(format)) {
            fillCompressedTexture(t, texture, format, width, height);
        } else if (multisampled) {
            fillMultisampledColorViaRender(
                t, texture, format, componentTypeForFormatAspect(formatId, aspectId));
        } else {
            fillEncodableColorTexture(t, texture, format, width, height);
        }

        // getTextureFormatTypeInfo(format, aspect).
        const std::string srcType = formatTypeForFormatAspect(formatId, aspectId);
        const std::string componentType = componentTypeForFormatAspect(formatId, aspectId);
        const std::string resultType =
            componentType == "u32" ? "vec4u" : componentType == "i32" ? "vec4i" : "vec4f";
        const std::string expFormatId = componentType == "u32"
            ? "rgba32uint"
            : componentType == "i32" ? "rgba32sint" : "rgba32float";
        const WGPUTextureFormat expFormat = parseTextureFormat(expFormatId);

        // Read the 4 source texels (through an identity view) in result format.
        const std::array<Color, 4> sampledColors =
            readSourceTexels(t, texture, format, aspectId, multisampled, componentType, x0, y0);

        std::array<Color, 4> readColors = {};
        for (size_t i = 0; i < 4; ++i) {
            readColors[i] = comparison ? applyCompareToTexel(sampledColors[i], compare, kDepthRef)
                                       : sampledColors[i];
        }

        // Per-view test data: swizzled expectation + swizzled texture view.
        const std::array<std::string, 2> swizzles = {swizzle, otherSwizzle};
        std::array<Color, 2> expColors = {};
        std::array<WGPUTextureView, 2> textureViews = {nullptr, nullptr};
        // Chained swizzle descriptors must outlive the createView calls below.
        std::array<WGPUTextureComponentSwizzleDescriptor, 2> swizzleDescs = {{
            WGPU_TEXTURE_COMPONENT_SWIZZLE_DESCRIPTOR_INIT,
            WGPU_TEXTURE_COMPONENT_SWIZZLE_DESCRIPTOR_INIT,
        }};
        for (size_t s = 0; s < 2; ++s) {
            std::array<Color, 4> swizzledColors = {};
            for (size_t i = 0; i < 4; ++i) {
                swizzledColors[i] = swizzleTexel(readColors[i], swizzles[s]);
            }
            if (isBuiltinGather(func)) {
                expColors[s] = gather(swizzledColors, channel);
            } else if (singleChannel) {
                const double r = swizzledColors[0][0];
                expColors[s] = Color{r, r, r, r};
            } else {
                expColors[s] = swizzledColors[0];
            }

            swizzleDescs[s].swizzle = makeSwizzle(swizzles[s]);
            WGPUTextureViewDescriptor viewDesc = WGPU_TEXTURE_VIEW_DESCRIPTOR_INIT;
            viewDesc.nextInChain = &swizzleDescs[s].chain;
            viewDesc.aspect = parseTextureAspect(aspectId);
            viewDesc.usage = WGPUTextureUsage_TextureBinding;
            textureViews[s] = t.createViewTracked(texture, viewDesc);
        }

        // Build the WGSL (mirrors upstream).
        const std::string samplerWGSL = comparison ? "sampler_comparison" : "sampler";
        std::ostringstream code;
        code << "      struct Uniforms {\n"
                "        texCoord: vec2f,\n"
                "      };\n"
                "\n"
                "      // These are intentionally in different bindGroups to test in compat that different swizzles\n"
                "      // of the same texture are not allowed.\n"
                "      @group(0) @binding(0) var tex0: "
             << input
             << ";\n"
                "      @group(1) @binding(0) var tex1: "
             << input
             << ";\n"
                "      @group(0) @binding(1) var smp: "
             << samplerWGSL
             << ";\n"
                "      @group(0) @binding(2) var<uniform> uni: Uniforms;\n"
                "      @group(0) @binding(3) var result: texture_storage_2d<"
             << expFormatId
             << ", write>;\n"
                "\n"
                "      @vertex fn vsFSResults() -> @builtin(position) vec4f {\n"
                "        return vec4f(0, 0, 0, 1);\n"
                "      }\n"
                "\n"
                "      @fragment fn fsFSResults() -> @location(0) vec4f {\n"
                "        let c0 = "
             << resultType << "(" << loadWGSL(func, input, channel, 0)
             << ");\n"
                "        let c1 = "
             << resultType << "(" << loadWGSL(func, input, channel, 1)
             << ");\n"
                "        textureStore(result, vec2u(0, 0), c0);\n"
                "        textureStore(result, vec2u(1, 0), c1);\n"
                "        return vec4f(0, 0, 0, 1);\n"
                "      }\n";
        WGPUShaderModule module = t.createShaderModuleTracked(code.str());

        // sampleType / samplerType (mirrors upstream).
        WGPUTextureSampleType sampleType;
        if (singleChannel) {
            sampleType = WGPUTextureSampleType_Depth;
        } else if (srcType == "depth") {
            sampleType = comparison ? WGPUTextureSampleType_Depth : WGPUTextureSampleType_UnfilterableFloat;
        } else if (srcType == "float" && multisampled) {
            sampleType = WGPUTextureSampleType_UnfilterableFloat;
        } else if (srcType == "uint") {
            sampleType = WGPUTextureSampleType_Uint;
        } else if (srcType == "sint") {
            sampleType = WGPUTextureSampleType_Sint;
        } else if (srcType == "unfilterable-float") {
            sampleType = WGPUTextureSampleType_UnfilterableFloat;
        } else {
            sampleType = WGPUTextureSampleType_Float;
        }
        const WGPUSamplerBindingType samplerType =
            comparison ? WGPUSamplerBindingType_Comparison : WGPUSamplerBindingType_NonFiltering;
        const WGPUShaderStage allStages =
            WGPUShaderStage_Compute | WGPUShaderStage_Fragment | WGPUShaderStage_Vertex;

        std::array<WGPUBindGroupLayoutEntry, 4> bgl0Entries = {{
            WGPU_BIND_GROUP_LAYOUT_ENTRY_INIT,
            WGPU_BIND_GROUP_LAYOUT_ENTRY_INIT,
            WGPU_BIND_GROUP_LAYOUT_ENTRY_INIT,
            WGPU_BIND_GROUP_LAYOUT_ENTRY_INIT,
        }};
        bgl0Entries[0].binding = 0;
        bgl0Entries[0].visibility = allStages;
        bgl0Entries[0].texture = WGPU_TEXTURE_BINDING_LAYOUT_INIT;
        bgl0Entries[0].texture.sampleType = sampleType;
        bgl0Entries[0].texture.multisampled = multisampled ? WGPU_TRUE : WGPU_FALSE;
        bgl0Entries[1].binding = 1;
        bgl0Entries[1].visibility = allStages;
        bgl0Entries[1].sampler = WGPU_SAMPLER_BINDING_LAYOUT_INIT;
        bgl0Entries[1].sampler.type = samplerType;
        bgl0Entries[2].binding = 2;
        bgl0Entries[2].visibility = allStages;
        bgl0Entries[2].buffer = WGPU_BUFFER_BINDING_LAYOUT_INIT;
        bgl0Entries[2].buffer.type = WGPUBufferBindingType_Uniform;
        bgl0Entries[3].binding = 3;
        bgl0Entries[3].visibility = WGPUShaderStage_Compute | WGPUShaderStage_Fragment;
        bgl0Entries[3].storageTexture = WGPU_STORAGE_TEXTURE_BINDING_LAYOUT_INIT;
        bgl0Entries[3].storageTexture.access = WGPUStorageTextureAccess_WriteOnly;
        bgl0Entries[3].storageTexture.format = expFormat;

        WGPUBindGroupLayoutDescriptor bgl0Desc = WGPU_BIND_GROUP_LAYOUT_DESCRIPTOR_INIT;
        bgl0Desc.entryCount = bgl0Entries.size();
        bgl0Desc.entries = bgl0Entries.data();
        WGPUBindGroupLayout bgl0 = t.createBindGroupLayoutTracked(bgl0Desc);

        WGPUBindGroupLayoutEntry bgl1Entry = WGPU_BIND_GROUP_LAYOUT_ENTRY_INIT;
        bgl1Entry.binding = 0;
        bgl1Entry.visibility = allStages;
        bgl1Entry.texture = WGPU_TEXTURE_BINDING_LAYOUT_INIT;
        bgl1Entry.texture.sampleType = sampleType;
        bgl1Entry.texture.multisampled = multisampled ? WGPU_TRUE : WGPU_FALSE;

        WGPUBindGroupLayoutDescriptor bgl1Desc = WGPU_BIND_GROUP_LAYOUT_DESCRIPTOR_INIT;
        bgl1Desc.entryCount = 1;
        bgl1Desc.entries = &bgl1Entry;
        WGPUBindGroupLayout bgl1 = t.createBindGroupLayoutTracked(bgl1Desc);

        const std::array<WGPUBindGroupLayout, 2> bindGroupLayouts = {bgl0, bgl1};
        WGPUPipelineLayoutDescriptor layoutDesc = WGPU_PIPELINE_LAYOUT_DESCRIPTOR_INIT;
        layoutDesc.bindGroupLayoutCount = bindGroupLayouts.size();
        layoutDesc.bindGroupLayouts = bindGroupLayouts.data();
        WGPUPipelineLayout pipelineLayout = t.createPipelineLayoutTracked(layoutDesc);

        WGPUColorTargetState colorTarget = WGPU_COLOR_TARGET_STATE_INIT;
        colorTarget.format = WGPUTextureFormat_RGBA8Unorm;

        WGPUFragmentState fragment = WGPU_FRAGMENT_STATE_INIT;
        fragment.module = module;
        fragment.entryPoint = stringView("fsFSResults");
        fragment.targetCount = 1;
        fragment.targets = &colorTarget;

        WGPURenderPipelineDescriptor pipelineDesc = WGPU_RENDER_PIPELINE_DESCRIPTOR_INIT;
        pipelineDesc.layout = pipelineLayout;
        pipelineDesc.vertex.module = module;
        pipelineDesc.vertex.entryPoint = stringView("vsFSResults");
        pipelineDesc.primitive.topology = WGPUPrimitiveTopology_PointList;
        pipelineDesc.fragment = &fragment;
        WGPURenderPipeline pipeline = t.createRenderPipelineTracked(pipelineDesc);

        // Output storage texture (zero-initialized by WebGPU; never pre-filled).
        WGPUTextureDescriptor outputDesc = WGPU_TEXTURE_DESCRIPTOR_INIT;
        outputDesc.format = expFormat;
        outputDesc.size = WGPUExtent3D{2, 1, 1};
        outputDesc.usage = WGPUTextureUsage_CopySrc | WGPUTextureUsage_StorageBinding;
        WGPUTexture outputTexture = t.createTextureTracked(outputDesc);
        WGPUTextureViewDescriptor outputViewDesc = WGPU_TEXTURE_VIEW_DESCRIPTOR_INIT;
        WGPUTextureView outputView = t.createViewTracked(outputTexture, outputViewDesc);

        WGPUSamplerDescriptor samplerDesc = WGPU_SAMPLER_DESCRIPTOR_INIT;
        if (comparison) {
            samplerDesc.compare =
                compare == "less" ? WGPUCompareFunction_Less : WGPUCompareFunction_Greater;
        }
        WGPUSampler sampler = t.createSamplerTracked(samplerDesc);

        WGPUBufferDescriptor uniformDesc = WGPU_BUFFER_DESCRIPTOR_INIT;
        uniformDesc.size = (2 + 2) * 4; // vec2f + padding
        uniformDesc.usage = WGPUBufferUsage_Uniform | WGPUBufferUsage_CopyDst;
        WGPUBuffer uniformBuffer = t.createBufferTracked(uniformDesc);
        std::array<float, 4> uniformValues = {
            static_cast<float>(tx / static_cast<double>(width)),
            static_cast<float>(ty / static_cast<double>(height)),
            0.0f,
            0.0f,
        };
        t.queueWriteBuffer(uniformBuffer, 0, uniformValues.data(), sizeof(uniformValues));

        std::array<WGPUBindGroupEntry, 4> bg0Entries = {{
            WGPU_BIND_GROUP_ENTRY_INIT,
            WGPU_BIND_GROUP_ENTRY_INIT,
            WGPU_BIND_GROUP_ENTRY_INIT,
            WGPU_BIND_GROUP_ENTRY_INIT,
        }};
        bg0Entries[0].binding = 0;
        bg0Entries[0].textureView = textureViews[0];
        bg0Entries[1].binding = 1;
        bg0Entries[1].sampler = sampler;
        bg0Entries[2].binding = 2;
        bg0Entries[2].buffer = uniformBuffer;
        bg0Entries[3].binding = 3;
        bg0Entries[3].textureView = outputView;

        WGPUBindGroupDescriptor bg0Desc = WGPU_BIND_GROUP_DESCRIPTOR_INIT;
        bg0Desc.layout = bgl0;
        bg0Desc.entryCount = bg0Entries.size();
        bg0Desc.entries = bg0Entries.data();
        WGPUBindGroup bindGroup0 = t.createBindGroupTracked(bg0Desc);

        WGPUBindGroupEntry bg1Entry = WGPU_BIND_GROUP_ENTRY_INIT;
        bg1Entry.binding = 0;
        bg1Entry.textureView = textureViews[1];

        WGPUBindGroupDescriptor bg1Desc = WGPU_BIND_GROUP_DESCRIPTOR_INIT;
        bg1Desc.layout = bgl1;
        bg1Desc.entryCount = 1;
        bg1Desc.entries = &bg1Entry;
        WGPUBindGroup bindGroup1 = t.createBindGroupTracked(bg1Desc);

        // 1x1 dummy color attachment.
        WGPUTextureDescriptor attachmentDesc = WGPU_TEXTURE_DESCRIPTOR_INIT;
        attachmentDesc.format = WGPUTextureFormat_RGBA8Unorm;
        attachmentDesc.size = WGPUExtent3D{1, 1, 1};
        attachmentDesc.usage = WGPUTextureUsage_RenderAttachment;
        WGPUTexture attachmentTexture = t.createTextureTracked(attachmentDesc);
        WGPUTextureViewDescriptor attachmentViewDesc = WGPU_TEXTURE_VIEW_DESCRIPTOR_INIT;
        WGPUTextureView attachmentView = t.createViewTracked(attachmentTexture, attachmentViewDesc);

        WGPURenderPassColorAttachment colorAttachment = WGPU_RENDER_PASS_COLOR_ATTACHMENT_INIT;
        colorAttachment.view = attachmentView;
        colorAttachment.loadOp = WGPULoadOp_Clear;
        colorAttachment.storeOp = WGPUStoreOp_Store;
        colorAttachment.clearValue = WGPUColor{0.0, 0.0, 0.0, 0.0};

        WGPURenderPassDescriptor passDesc = WGPU_RENDER_PASS_DESCRIPTOR_INIT;
        passDesc.colorAttachmentCount = 1;
        passDesc.colorAttachments = &colorAttachment;

        WGPUCommandEncoder encoder = t.createCommandEncoderTracked();
        WGPURenderPassEncoder pass = wgpuCommandEncoderBeginRenderPass(encoder, &passDesc);
        wgpuRenderPassEncoderSetPipeline(pass, pipeline);
        wgpuRenderPassEncoderSetBindGroup(pass, 0, bindGroup0, 0, nullptr);
        wgpuRenderPassEncoderSetBindGroup(pass, 1, bindGroup1, 0, nullptr);
        wgpuRenderPassEncoderDraw(pass, 1, 1, 0, 0);
        wgpuRenderPassEncoderEnd(pass);
        WGPUCommandBuffer commandBuffer = t.finishTracked(encoder);
        // Note: upstream expects a validation error here in compatibility mode when
        // the two swizzles differ; core backends accept differing swizzles.
        wgpuQueueSubmit(t.queue(), 1, &commandBuffer);

        // Copy the 2x1 output texture to a buffer and compare both texels.
        constexpr uint32_t kExpBytesPerTexel = 16;
        WGPUBufferDescriptor readbackDesc = WGPU_BUFFER_DESCRIPTOR_INIT;
        readbackDesc.size = 2 * kExpBytesPerTexel;
        readbackDesc.usage = WGPUBufferUsage_CopyDst | WGPUBufferUsage_CopySrc;
        WGPUBuffer readbackBuffer = t.createBufferTracked(readbackDesc);

        WGPUCommandEncoder copyEncoder = t.createCommandEncoderTracked();
        t.copyTextureToBuffer(copyEncoder, outputTexture, readbackBuffer, kBytesPerRowAlignment,
                              WGPUExtent3D{2, 1, 1});
        WGPUCommandBuffer copyCommandBuffer = t.finishTracked(copyEncoder);
        wgpuQueueSubmit(t.queue(), 1, &copyCommandBuffer);

        const char componentKind = componentType[0]; // 'f', 'u', or 'i'
        t.expectGPUBufferValuesPassCheck(
            readbackBuffer,
            [&](const uint8_t* actual, size_t len) -> std::optional<std::string> {
                for (size_t i = 0; i < 2; ++i) {
                    for (size_t ch = 0; ch < 4; ++ch) {
                        const size_t offset = i * kExpBytesPerTexel + ch * 4;
                        if (offset + 4 > len) {
                            return std::string("output readback too short");
                        }
                        const double expected = expColors[i][ch];
                        double got = 0.0;
                        if (componentKind == 'u') {
                            uint32_t v = 0;
                            std::memcpy(&v, actual + offset, sizeof(v));
                            got = static_cast<double>(v);
                        } else if (componentKind == 'i') {
                            int32_t v = 0;
                            std::memcpy(&v, actual + offset, sizeof(v));
                            got = static_cast<double>(v);
                        } else {
                            float v = 0.0f;
                            std::memcpy(&v, actual + offset, sizeof(v));
                            got = static_cast<double>(v);
                        }

                        bool ok;
                        if (componentKind == 'f') {
                            ok = (std::isnan(expected) && std::isnan(got)) || expected == got
                                || std::fabs(expected - got) <= 0.01;
                        } else {
                            ok = expected == got;
                        }
                        if (!ok) {
                            std::ostringstream message;
                            message << "swizzle mismatch: view " << i << " (swizzle '" << swizzles[i]
                                    << "') channel " << "rgba"[ch] << ": expected " << expected
                                    << ", got " << got << " (format=" << formatId << ", func=" << func
                                    << ", aspect=" << aspectId << ", input=" << input << ")";
                            return message.str();
                        }
                    }
                }
                return std::nullopt;
            },
            0,
            static_cast<size_t>(readbackDesc.size));
    });

} // namespace
